### ISSUE TITLE
DVP Constellations Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [luckyguy73/Codecademy-orion-constellation#1]
### Criteria 1: Matplotlib and CSV
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, the Jupyter notebook file imports the libraries necessary for the project.
 
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, the 2D grid appears with data plotted on the graph and the visualization includes custom color and a title.
 
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good, the 3D grid appears with the correct data plotted on the graph. The grid is rotatable, and there is a title on the graph.
 
### Overall Score: 12/12
Great job overall! Your project included all of the required components, and your visualizations were well done.

**Comment by luckyguy73** [comment]
awesome, thanks Mackenzie!
